name: Dependencies Example
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  dependencies-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sets up NPM framework
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          cache: 'npm'

      - name: Verify
        run: ls -alhR
        
